name: Deploy to Algorithmia

on:
  push:
    branches:
      - master

jobs:
  algorithmia-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2.0.0
        with:
          ref: ${{github.sha}}
      - name: Deploy Model to Algorithmia
        uses: algorithmiaio/algorithmia-modeldeployment-action@1.0.1
        env:
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
        with:
          algorithmia_api_key: ${{ secrets.ALGORITHMIA_API_KEY }}
          algorithmia_username: ${{ secrets.ALGORITHMIA_USERNAME }}
          algorithmia_email: ${{ secrets.ALGORITHMIA_EMAIL }}
          algorithmia_password: ${{ secrets.ALGORITHMIA_PASSWORD }}
          algorithmia_algoname: distilbert_multiclass_classifier
          git_host: git.algorithmia.com
          model_path: checkpoint.pth
          notebook_path: train_validate_distilbert_multiclass.ipynb

