name: Deploy to Algorithmia

on:
  push:
    branches:
      - master

jobs:
  algorithmia-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2.0.0
        with:
          ref: ${{github.sha}}
      - name: Deploy Model to Algorithmia
        uses: algorithmiaio/algorithmia-modeldeployment-action@master
        env:
          HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        with:
          algorithmia_api_key: ${{ secrets.ALGORITHMIA_API_KEY }}
          algorithmia_username: ${{ secrets.ALGORITHMIA_USERNAME }}
          algorithmia_email: ${{ secrets.ALGORITHMIA_EMAIL }}
          algorithmia_password: ${{ secrets.ALGORITHMIA_PASSWORD }}
          algorithmia_algoname: distilbert_multiclass_classifier
          git_host: git.devopsbay1.enthalpy.click
          model_path: distilbert-checkpoints.pth
          notebook_path: train_validate_distilbert_multiclass.ipynb

